// Per-style moodboards (spec: docs/superpowers/specs/2026-09-28-moodboard-design.md, ADR-0018).
// moodboard.json lists 6 self-made studies per style (committed) and the source of each referenced
// work (for local stills only). The studies are compositions in a host generated like the example
// hosts; `sheets` renders them and tiles one sheet per style; `fetch` downloads the real stills into
// the gitignored local/ folder. Node 22+, built-in modules only (ADR-0007); rendering needs
// `npx hyperframes`, `cwebp`, and `ffmpeg`.
import { spawnSync } from 'node:child_process';
import { cpSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { EXAMPLES, hostHtml, PREFIX, snapshots, STYLES } from './style-examples.mjs';

export const MB = 'docs/agents/references/moodboard';
export const LOCAL = `${MB}/local`;
const HYPERFRAMES = 'hyperframes@0.7.24';
const PER_STYLE = 6;

export const readMoodboard = (root) => JSON.parse(readFileSync(join(root, MB, 'moodboard.json'), 'utf8'));

// the studies in host order: styles in STYLES order, s1…s6 inside each
export const ordered = (m) => STYLES.flatMap((st) => m.studies.filter((s) => s.style === st));

export function checkMoodboard(m, docs = {}) {
  const ids = new Set();
  for (const st of STYLES) {
    const list = m.studies.filter((s) => s.style === st);
    if (list.length !== PER_STYLE) throw new Error(`${st}: needs ${PER_STYLE} studies, has ${list.length}`);
  }
  for (const s of m.studies) {
    if (!STYLES.includes(s.style)) throw new Error(`${s.id}: unknown style "${s.style}"`);
    if (!new RegExp(`^${PREFIX[s.style]}-s[1-${PER_STYLE}]$`).test(s.id)) throw new Error(`${s.id}: a ${s.style} study is ${PREFIX[s.style]}-s1 … -s${PER_STYLE}`);
    if (ids.has(s.id)) throw new Error(`${s.id}: listed twice`);
    ids.add(s.id);
    if (!/^R\d+$/.test(s.ref)) throw new Error(`${s.id}: ref must look like R3`);
    if (docs[s.style] && !new RegExp(`^### ${s.ref} — `, 'm').test(docs[s.style])) throw new Error(`${s.id}: ${s.style}.md has no ### ${s.ref}`);
    if (!s.title || !s.steal) throw new Error(`${s.id}: needs a title and a steal line`);
    if (!(s.duration > 0) || !(s.at >= 0 && s.at < s.duration)) throw new Error(`${s.id}: at must be inside the study`);
    if (!m.refs.some((r) => r.style === s.style && r.ref === s.ref)) throw new Error(`${s.id}: no refs entry for ${s.style} ${s.ref}`);
  }
  for (const r of m.refs) if (!/^https:\/\//.test(r.source ?? '')) throw new Error(`${r.style} ${r.ref}: source must be an https URL`);
  return m;
}

// the studies host: the example host generator, renamed, with every study as a cutaway clip
export function studiesHost(m) {
  const ex = { style: 'moodboard', examples: ordered(m).map((s) => ({ clip: s.id, duration: s.duration, treatment: 'cutaway', stills: [s.at] })) };
  const html = hostHtml(ex)
    .replaceAll('style-examples-moodboard', 'moodboard-studies')
    .replace('from examples.json', 'from moodboard.json')
    .replace('npm run style-examples -- build', 'npm run moodboard -- build');
  return {
    [`${MB}/studies/index.html`]: html,
    [`${MB}/studies/snapshots.json`]: JSON.stringify(snapshots(ex)) + '\n',
  };
}

const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));

// one sheet per style: 3 × 2 tiles of the study frames with the reference and what it steals
export function sheetHtml(style, studies) {
  const id = `moodboard-${style}`;
  const tiles = studies.map((s) => `<div class="c"><img src="frames/${s.id}.png" alt="" /><div class="r">${esc(s.ref)} · ${esc(s.id)}</div><div class="n">${esc(s.title)}</div><div class="s">${esc(s.steal)}</div></div>`).join('');
  return `<!doctype html>
<html>
  <head><meta charset="UTF-8" /></head>
  <body>
    <!-- GENERATED by \`npm run moodboard -- sheets\` from moodboard.json; do not edit. -->
    <template>
      <style>
        #root { position: absolute; inset: 0; }
        .t { position: absolute; left: 40px; top: 36px; font-size: 40px; font-weight: 700; color: #1c1917; }
        .w { position: absolute; left: 40px; top: 92px; font-size: 22px; color: #b91c1c; }
        .g { position: absolute; left: 30px; top: 150px; right: 30px; display: grid; grid-template-columns: repeat(3, 1fr); gap: 18px; }
        .c { background: #fbfaf6; border-radius: 10px; padding: 8px; overflow: hidden; }
        .c img { display: block; width: 100%; aspect-ratio: 9 / 16; object-fit: cover; border-radius: 4px; }
        .r { margin-top: 8px; font-size: 18px; font-weight: 700; color: #57534e; }
        .n { margin-top: 2px; font-size: 20px; font-weight: 700; line-height: 1.15; color: #1c1917; }
        .s { margin-top: 4px; font-size: 17px; line-height: 1.2; color: #57534e; }
      </style>
      <div id="root" data-composition-id="${id}" data-width="1080" data-height="1920" data-duration="1">
        <div class="sk-stage sk-f-geist" style="background:#ecebe7">
          <div class="t">moodboard · ${esc(style)}</div>
          <div class="w">self-made studies of each technique — not the original works</div>
          <div class="g">${tiles}</div>
        </div>
      </div>
      <script>
        (() => {
          const ID = '${id}';
          SK.clip(ID, { T: 1, update: () => {} });
        })();
      </script>
    </template>
  </body>
</html>
`;
}

function sheetsIndex(styles) {
  const mounts = styles.map((st, i) => `      <div id="moodboard-${st}-mount" class="sheet" data-composition-id="moodboard-${st}" data-composition-src="compositions/${st}.html"
           data-start="${i}" data-duration="1" data-track-index="1" data-width="1080" data-height="1920"></div>`).join('\n');
  return `<!doctype html>
<html lang="id">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=1080, height=1920" />
    <script src="vendor/gsap.min.js"></script>
    <script src="vendor/motion-kit/motion-kit.js"></script>
    <script src="vendor/style-kit/style-kit.js"></script>
    <script src="vendor/asset-lib/asset-lib.js"></script>
    <link rel="stylesheet" href="vendor/motion-kit/motion-kit.css" />
    <link rel="stylesheet" href="vendor/style-kit/style-kit.css" />
    <link rel="stylesheet" href="vendor/asset-lib/asset-lib.css" />
    <style>
      body { margin: 0; background: #ecebe7; }
      #root { position: relative; width: 1080px; height: 1920px; overflow: hidden; background: #ecebe7; }
      .sheet { position: absolute; inset: 0; }
    </style>
  </head>
  <body>
    <div id="root" data-composition-id="moodboard-sheets" data-start="0" data-width="1080" data-height="1920" data-duration="${styles.length}">
${mounts}
    </div>
    <script>
      window.__timelines = window.__timelines || {};
      window.__timelines['moodboard-sheets'] = gsap.timeline({ paused: true });
    </script>
  </body>
</html>
`;
}

function hfRunner() {
  const env = { ...process.env };
  delete env.GEMINI_API_KEY; // snapshot would otherwise send frames to Gemini for --describe
  return (...args) => { const r = spawnSync('npx', ['--yes', HYPERFRAMES, ...args], { stdio: 'inherit', env }); if (r.status !== 0) throw new Error(`hyperframes ${args[0]} failed`); };
}

function copyVendor(root, dir) {
  mkdirSync(join(dir, 'vendor'), { recursive: true });
  cpSync(join(root, 'vendor/gsap.min.js'), join(dir, 'vendor/gsap.min.js'));
  for (const v of ['motion-kit', 'style-kit', 'paper-pack']) cpSync(join(root, 'vendor', v), join(dir, 'vendor', v), { recursive: true });
  cpSync(join(root, 'vendor/asset-lib'), join(dir, 'vendor/asset-lib'), { recursive: true, filter: (f) => !f.includes('/src') });
}

// render the studies of the given styles (default all) at their stills, tile one sheet per style,
// write sheets/<style>.webp; only those styles' compositions need to exist
export function buildSheets(root, only = STYLES) {
  const m = checkMoodboard(readMoodboard(root));
  const sub = { ...m, studies: m.studies.filter((s) => only.includes(s.style)) };
  const hf = hfRunner();
  const dir = mkdtempSync(join(tmpdir(), 'moodboard-'));
  try {
    // 1. the studies: a host of just these studies + their compositions + shared example assets
    const sd = join(dir, 'studies');
    mkdirSync(join(sd, 'compositions'), { recursive: true });
    for (const s of sub.studies) cpSync(join(root, MB, 'studies/compositions', `${s.id}.html`), join(sd, 'compositions', `${s.id}.html`));
    for (const [p, c] of Object.entries(studiesHost(sub))) writeFileSync(join(sd, p.slice(`${MB}/studies/`.length)), c);
    cpSync(join(root, MB, 'studies/hyperframes.json'), join(sd, 'hyperframes.json'));
    copyVendor(root, sd);
    cpSync(join(root, EXAMPLES, 'assets'), join(sd, 'assets'), { recursive: true });
    hf('lint', sd);
    hf('validate', sd);
    const { at } = JSON.parse(readFileSync(join(sd, 'snapshots.json'), 'utf8'));
    hf('snapshot', '--at', at.join(','), '-o', join(dir, 'frames-raw'), sd);
    const raw = readdirSync(join(dir, 'frames-raw')).filter((f) => /^frame-\d+/.test(f)).sort();
    const list = ordered(sub);
    if (raw.length !== list.length) throw new Error(`expected ${list.length} study frames, got ${raw.length}`);
    // 2. the sheets: one page per style over the study frames
    const pd = join(dir, 'sheets');
    mkdirSync(join(pd, 'frames'), { recursive: true });
    mkdirSync(join(pd, 'compositions'), { recursive: true });
    list.forEach((s, i) => cpSync(join(dir, 'frames-raw', raw[i]), join(pd, 'frames', `${s.id}.png`)));
    for (const st of only) writeFileSync(join(pd, 'compositions', `${st}.html`), sheetHtml(st, list.filter((s) => s.style === st)));
    writeFileSync(join(pd, 'index.html'), sheetsIndex(only));
    writeFileSync(join(pd, 'hyperframes.json'), JSON.stringify({ id: 'moodboard-sheets', name: 'Moodboard sheets' }, null, 2) + '\n');
    copyVendor(root, pd);
    hf('lint', pd);
    hf('snapshot', '--at', only.map((_, i) => i + 0.5).join(','), '-o', join(dir, 'pages'), pd);
    const pages = readdirSync(join(dir, 'pages')).filter((f) => /^frame-\d+/.test(f)).sort();
    const out = join(root, MB, 'sheets');
    mkdirSync(out, { recursive: true });
    pages.forEach((f, i) => {
      const r = spawnSync('cwebp', ['-quiet', '-q', '78', join(dir, 'pages', f), '-o', join(out, `${only[i]}.webp`)]);
      if (r.status !== 0) throw new Error(`cwebp failed for ${f}`);
    });
    return `${pages.length} sheets → ${MB}/sheets/`;
  } finally { rmSync(dir, { recursive: true, force: true }); }
}

// og:image (or twitter:image) of an HTML page, resolved against the page URL
export function ogImage(html, base) {
  const m = html.match(/<meta[^>]+(?:property|name)=["'](?:og:image|twitter:image)["'][^>]*>/i);
  const c = m && m[0].match(/content=["']([^"']+)["']/i);
  return c ? new URL(c[1].replace(/&amp;/g, '&'), base).href : null;
}

const EXT = { 'image/jpeg': 'jpg', 'image/png': 'png', 'image/webp': 'webp', 'image/gif': 'gif' };

// download the real stills of a style into local/<style>/ (never anywhere else); failures are skipped
export async function fetchRefs(root, style, { fetchImpl = fetch, log = console.log } = {}) {
  const m = readMoodboard(root);
  const out = join(root, LOCAL, style);
  const done = [];
  for (const r of m.refs.filter((x) => x.style === style)) {
    try {
      let url = r.image;
      if (!url) {
        const page = await fetchImpl(r.source, { headers: { 'user-agent': 'Mozilla/5.0 (moodboard reference fetch)' } });
        if (!page.ok) throw new Error(`HTTP ${page.status} for the source page`);
        url = ogImage(await page.text(), r.source);
        if (!url) throw new Error('no og:image on the source page');
      }
      const img = await fetchImpl(url, { headers: { 'user-agent': 'Mozilla/5.0 (moodboard reference fetch)' } });
      if (!img.ok) throw new Error(`HTTP ${img.status} for the image`);
      const type = (img.headers.get('content-type') || '').split(';')[0].trim();
      const ext = EXT[type];
      if (!ext) throw new Error(`not an image (${type || 'no content-type'})`);
      mkdirSync(out, { recursive: true });
      const file = join(out, `${r.ref}.${ext}`);
      writeFileSync(file, Buffer.from(await img.arrayBuffer()));
      done.push({ ref: r.ref, file });
      log(`  ${style} ${r.ref}: saved`);
    } catch (e) {
      log(`  ${style} ${r.ref}: skipped (${e.message})`);
    }
  }
  return done;
}

// tile the fetched stills of a style into local/<style>.webp (3 × 2, 9:16 cells)
export function localSheet(root, style, files) {
  if (!files.length) return null;
  const dir = mkdtempSync(join(tmpdir(), 'moodboard-local-'));
  try {
    const cells = files.slice(0, 6);
    const inputs = cells.flatMap((f) => ['-i', f.file]);
    const scaled = cells.map((_, i) => `[${i}]scale=340:604:force_original_aspect_ratio=decrease,pad=340:604:(ow-iw)/2:(oh-ih)/2:color=0xecebe7[v${i}]`);
    const pad = Array.from({ length: 6 - cells.length }, (_, k) => `color=c=0xecebe7:s=340x604:d=1[v${cells.length + k}]`);
    const stack = `${Array.from({ length: 6 }, (_, i) => `[v${i}]`).join('')}xstack=inputs=6:layout=0_0|350_0|700_0|0_614|350_614|700_614:fill=0xecebe7`;
    const png = join(dir, 'sheet.png');
    const r = spawnSync('ffmpeg', ['-loglevel', 'error', '-y', ...inputs, '-filter_complex', [...scaled, ...pad, stack].join(';'), '-frames:v', '1', png]);
    if (r.status !== 0) throw new Error(`ffmpeg failed: ${r.stderr}`);
    const out = join(root, LOCAL, `${style}.webp`);
    const w = spawnSync('cwebp', ['-quiet', '-q', '78', png, '-o', out]);
    if (w.status !== 0) throw new Error('cwebp failed');
    return out;
  } finally { rmSync(dir, { recursive: true, force: true }); }
}
