from pathlib import Path
import json, re, shutil, sys

SCRIPT=Path(__file__).resolve()
if SCRIPT.parent.name == 'scripts':
    R=SCRIPT.parents[1]
    P=Path(sys.argv[1]).resolve() if len(sys.argv)>1 else R/'videos/style-atelier'
else:
    P=SCRIPT.parents[1]
    R=P.parents[1]
for d in ['assets/fonts','compositions','preview','.hyperframes','vendor']:(P/d).mkdir(parents=True,exist_ok=True)
for name,src in [('Archivo','asset-lib/fonts/archivo-black-latin-400-normal.woff2'),('Serif','asset-lib/fonts/instrument-serif-latin-400-normal.woff2'),('Mono','asset-lib/fonts/jetbrains-mono-latin-wght-normal.woff2'),('Hand','style-kit/fonts/Caveat-Variable.woff2')]:
    dst=P/'assets/fonts'/f'{name}.woff2'
    if not dst.exists():shutil.copy2(R/'vendor'/src,dst)
for src in ['asset-lib/fonts/OFL-archivo-black.txt','asset-lib/fonts/OFL-instrument-serif.txt','asset-lib/fonts/OFL-jetbrains-mono.txt','style-kit/fonts/OFL-Caveat.txt']:
    if (R/'vendor'/src).exists():shutil.copy2(R/'vendor'/src,P/'assets/fonts'/Path(src).name)
for name,src in [('gsap.min.js','vendor/gsap.min.js'),('motion-kit.js','vendor/motion-kit/motion-kit.js'),('style-kit.js','vendor/style-kit/style-kit.js')]:
    if not (P/'vendor'/name).exists():shutil.copy2(R/src,P/'vendor'/name)

scenes=[
('text-mask','broll-text','MAKE IT MATTER.','Masked poster type, offset print and registration.','ink'),
('text-tempo','broll-text','TYPE HAS TEMPO.','Alternating scale and direction; a folded type ribbon.','acid'),
('mg-orbit','motion-graphic','IDEA → SYSTEM.','Stage the relationship, then reveal six connected nodes.','paper'),
('mg-flow','motion-graphic','ONE FLOW. MANY ROUTES.','Draw a single branching relation with a travelling signal.','blue'),
('wb-flow','whiteboard','THINK IT THROUGH.','Authored pen order with the marker attached to the current stroke.','paper'),
('wb-loop','whiteboard','IDEAS CONNECT.','A feedback loop closes around a handwritten concept.','paper'),
('stop-fan','stop-motion','FOLD A POSSIBILITY.','Paper leaves hinge open on twos; hard contact shadows.','pink'),
('stop-envelope','stop-motion','SEND THE IDEA.','Envelope card, flap and folded plane on held two-frame poses.','paper'),
('vox-detail','vox','FOLLOW THE DETAIL.','Illustrative document, stepped push, one highlight, then a hold.','paper'),
('vox-timeline','vox','SEE THE CONNECTION.','Four illustrative editorial cards linked by a red pen line.','ink'),
('mm-story','mix-media','MAKE SPACE FOR STORY.','Ripped paper and frames leave a labelled speaker slot clear.','pink'),
('mm-play','mix-media','CUT. PASTE. PLAY.','Pasted live letters, a paper frame, xerox marks and sticker punctuation.','acid'),
('px-mountains','parallax','ROOM TO IMAGINE.','Three original vector planes, small orbit and a restrained dolly.','ink'),
('px-city','parallax','A DIFFERENT POINT OF VIEW.','Original city planes at dusk; a slow lateral camera move.','ink'),
('material','showreel','MATTER IN MOTION.','Metallic ribbon, faceted prism and a sculptural star.','ink'),
('finale','showreel','RICHER BY DESIGN.','Petal sculpture and orbital geometry resolve into the Atelier identity.','ink'),
]
rows=[{'id':f'atelier-{i+1:02}-{k}','key':k,'style':sty,'title':title,'concept':concept,'theme':theme,'start':i*4,'duration':4,'source':f'compositions/{i+1:02}-{k}.html'} for i,(k,sty,title,concept,theme) in enumerate(scenes)]
(P/'overlay-timeline.json').write_text(json.dumps({'version':1,'scenes':rows},indent=2))
(P/'metadata.json').write_text(json.dumps({'slug':'style-atelier','title':'ATELIER / Richer by Design','duration':64,'width':1920,'height':1080,'fps':30,'scope':'motion-asset-pack'},indent=2))
(P/'sources.json').write_text(json.dumps({'version':1,'sources':[]},indent=2))
(P/'creative-brief.md').write_text('# ATELIER / Richer by Design\n\nUser scope: enrich all seven style-library families plus FORM / FREQUENCY assets. Standalone asset collection and locally rendered demonstration; no Dena narration or publish action. 112 original layered SVGs, 16 four-second scenes, 64 seconds, 1920×1080, 30 fps.\n\nConcept: a motion atelier turns an idea into type, relation, sketch, paper, document, collage, layered world and sculptural material.\n')
(P/'design.md').write_text('# Atelier design\n\nInk #171918, paper #F1EEE5, cobalt #244BFF, vermilion #FA593D, acid #D9FC59, lilac #B6A3EF. Shared with FORM / FREQUENCY; varied family fields demonstrate range, rather than prescribing a mix of seven styles for one actual edit. Archivo Black for large display, Instrument Serif for expressive editorial copy, JetBrains Mono for edge furniture, Caveat for authored sketch labels. All local with OFL licenses.\n\n80 px title-safe border; heroes 900–1400 px wide, display 135–235 px, labels 26–34 px. Quiet label zones. Background texture, single strong hero, secondary live type, accent geometry, registration, chapter meter and fine rules.\n\nRhythm: slam / stretch / build / route / draw / close / unfold / launch / focus / connect / gather / paste / breathe / drift / sculpt / resolve. Two bars per scene at 120 BPM. Hard chapter cuts retain the last reading pose; entrances inherit directional energy. Paper, VOX and collage quantize every graphic pose to 15 steps/s. No paper blur or crossfades.\n')
(P/'storyboard.md').write_text('# Sixteen style studies\n\n'+''.join(f'{i+1:02}. {r["start"]}–{r["start"]+4}s — **{r["title"]}** ({r["style"]}) — {r["concept"]}\n\n' for i,r in enumerate(rows)))
(P/'visual-plan.md').write_text('# Visual plan\n\n## Style world\n\nAn asset-library demonstration, with two contrasting studies per family. Palette and typography: design.md. This collection demonstrates options; actual Dena edits choose at most three style types, semantically tied to the transcript.\n\n## Visual Decision Log\n\n'+''.join(f'- {r["id"]}: purpose demonstrate {r["style"]}; original designed SVGs with independent named parts; {r["concept"]} No proof captures or invented client results.\n' for r in rows)+'\n## Assembly\n\nTrack 1: sequential full-frame scene mounts. Track 20: original mastered music + SFX. Sixteen self-contained templates; SVG parts inline at setup, unique ids per instance; local SK.clip registers one deterministic paused timeline per study. Mix-media is a template study with a labelled speaker slot; production substitutes the exact-window real matte.\n\n## Review result\n\nUser explicitly chose all seven styles plus the showreel. Asset-production scope authorizes local source generation, assembly and rendering. Publish remains separate.\n')
(P/'.hyperframes/expanded-prompt.md').write_text('# ATELIER — Expanded production breakdown\n\nDesign spec: design.md. Fonts: Archivo Black, Instrument Serif, JetBrains Mono, Caveat. Palette #171918 / #F1EEE5 / #244BFF / #FA593D / #D9FC59 / #B6A3EF.\n\nRhythm: slam-stretch-build-route-draw-close-unfold-launch-focus-connect-gather-paste-breathe-drift-sculpt-resolve.\n\n'+''.join(f'## {i+1:02} — {r["title"]}\n\nConcept: {r["concept"]}\nMood: working design atelier; tactile construction and precise hierarchy.\nBG: full-bleed {r["theme"]} field, sparse structural grid, subtle paper/print material, moving chapter meter.\nMG: independent {r["style"]} hero parts; live display copy reveals on successive half-beats; focus lands by local 2.8s and holds.\nFG: 80px safe edge labels, registration crosses, source/illustration note, short accent rule.\nChoreography: {r["concept"]} Secondary motifs shift once after landing, then settle.\nTransition out: hard chapter cut at {r["start"]+4}s; direction inherited by the next study. SFX marks each major material gesture, quieter sketch/document gestures and deeper sculptural attacks.\n\n' for i,r in enumerate(rows))+'Negative direction: no fake Dena, real outlet, metric, remote dependency, wall-clock motion, endless decorative bouncing, or generic palette variants.\n')

css='''@font-face{font-family:Archivo;src:url(fonts/Archivo.woff2)}@font-face{font-family:Serif;src:url(fonts/Serif.woff2)}@font-face{font-family:Mono;src:url(fonts/Mono.woff2)}@font-face{font-family:Hand;src:url(fonts/Hand.woff2);font-weight:400 700}
*{box-sizing:border-box}html,body{margin:0}.sk-stage{position:absolute;inset:0;overflow:hidden;--sk-font-display:Archivo;--sk-font-body:Mono;--sk-font-serif:Serif;--sk-font-hand:Hand;--sk-font-mono:Mono}.sk-display{font-family:var(--sk-font-display);font-weight:400}.sk-serif{font-family:var(--sk-font-serif);font-weight:400}.sk-hand{font-family:var(--sk-font-hand);font-weight:700}.sk-mono{font-family:var(--sk-font-mono);font-weight:400}
'''
(P/'assets/design.css').write_text(css)

def art(name,family,asset,x,y,w,h=None,cls='',extra=''):
    src=R/'vendor/asset-lib/artwork/atelier'/family/f'{asset}.svg'
    if not src.exists():src=P/'assets/artwork'/family/f'{asset}.svg'
    svg=src.read_text().replace('role="img"','role="img" data-layout-allow-overflow data-layout-allow-overlap'); prefix=name+'-'
    for a in re.findall(r'id="([^"]+)"',svg):svg=svg.replace(f'id="{a}"',f'id="{prefix+a}"').replace(f'url(#{a})',f'url(#{prefix+a})')
    return f'<div class="art {cls}" data-art="{name}" data-layout-allow-overflow data-layout-allow-overlap data-layout-allow-occlusion style="left:{x}px;top:{y}px;width:{w}px;height:{h or w*.75}px" {extra}>{svg}</div>'

def title(words,x=85,y=208,size=165,cls='',width=850):
    return f'<div class="headline sk-display {cls}" style="left:{x}px;top:{y}px;font-size:{size}px;width:{width}px">'+''.join(f'<div class="mask"><span class="word">{s}</span></div>' for s in words)+'</div>'

def label(text,x,y,w=700,cls='',size=29):
    font=cls if cls.startswith('sk-') else 'sk-mono '+cls
    return f'<div class="label {font}" style="left:{x}px;top:{y}px;width:{w}px;font-size:{size}px">{text}</div>'

def placeholder(x,y,s=1):
    return f'<div class="speaker" data-layout-allow-overlap style="left:{x}px;top:{y}px;transform:scale({s});transform-origin:bottom center"><svg viewBox="0 0 420 700" width="420" height="700"><circle cx="210" cy="145" r="88" fill="#171918" stroke="#f1eee5" stroke-width="13"/><path d="M59 700V386Q59 253 210 253Q361 253 361 386V700Z" fill="#171918" stroke="#f1eee5" stroke-width="13"/></svg><div class="speaker-note sk-mono">SPEAKER SLOT</div></div>'

body={}; anim={}; style={}
body['text-mask']=title(['MAKE IT','MATTER.'],size=195,y=224,width=1160)+art('riso','text','riso-field',1170,160,620)+art('reg','text','registration',70,555,870)+label('An idea deserves a gesture.',96,784,850,'sk-serif',72)+art('quote','text','quotation',1450,635,350)
body['text-mask']+='<div class="print-specimen sk-serif" data-layout-allow-overlap>Aa</div>'
anim['text-mask']="""words(t,.12,.2,'mask');move(a('riso'),{x:160*(1-E(t,.28,.55)),r:-8+8*E(t,.28,.55),s:.8+.2*E(t,.28,.55)});move(a('reg'),{s:.94+.06*E(t,.55,.7)});move(a('quote'),{r:-18+18*E(t,1.8,.4),o:E(t,1.8,.15)});"""
style['text-mask']='.headline{z-index:5}.art[data-art=reg]{opacity:.15}.art[data-art=riso]{z-index:1}.label.sk-serif{z-index:5}.print-specimen{position:absolute;left:1350px;top:255px;font-size:230px;line-height:1;color:#171918;z-index:2;transform:rotate(-3deg)}'
body['text-tempo']=title(['TYPE HAS','TEMPO.'],size=205,y=193,width=1480)+art('banner','text','fold-banner',230,560,1460)+f'<div class="tempo sk-serif" data-layout-allow-overlap style="left:750px;top:700px">ta—ta—ta.</div>'+art('guide','text','radial-guide',1430,186,340)+label('SCALE / DIRECTION / RHYTHM',98,899,900)
anim['text-tempo']="""words(t,.1,.35,'slam');move(a('banner'),{x:-600*(1-E(t,.75,.5)),r:-5*E(t,.75,.5)});move(q('.tempo'),{y:130*(1-E(t,1.25,.5)),o:E(t,1.25,.1),r:-5});move(a('guide'),{r:45*t});move(q('.headline'),{x:-35*E(t,2.6,.4)});"""
style['text-tempo']='.tempo{position:absolute;font-size:115px;color:#f1eee5;z-index:3}.art[data-art=banner]{height:570px!important}.art[data-art=banner] [data-part=face] rect{fill:#244bff}.headline{z-index:4}'
body['mg-orbit']=title(['IDEA','TO SYSTEM.'],size=132,y=257,width=900)+art('network','mg','orbit-nodes',840,103,1030)+label('RELATIONSHIP STUDY / RELATIVE SHAPES',94,835,760,size=24)+label('One shared centre.',1073,839,750,'sk-serif',63)+art('modules','mg','modular-grid',76,594,270)
anim['mg-orbit']="""words(t,.12,.3,'rise');parts('network','spokes path').forEach((e,i)=>SK.draw(e,E(t,.4+i*.07,.5)));parts('network','node-').forEach((e,i)=>originMove(e,{s:.2+.8*spring(t,.7+i*.12),o:E(t,.7+i*.12,.1)},400,300));originMove(part('network','core'),{s:.3+.7*spring(t,.2),o:E(t,.2,.1)},400,300);move(a('modules'),{r:90*E(t,2.2,.6),s:.75+.25*E(t,.8,.6)});"""
body['mg-flow']=title(['ONE FLOW.','MANY','ROUTES.'],size=124,y=252,width=750)+art('flow','mg','branch-flow',805,162,1020)+label('A',908,509,60,'node-a',38)+label('B',1450,332,100,'node-b',38)+label('C',1450,689,100,'node-c',38)+label('ILLUSTRATIVE RELATION / NO CLAIMED VALUES',96,888,1100,size=24)
anim['mg-flow']="""words(t,.12,.24,'mask');part('flow','split').querySelectorAll('path').forEach((p,i)=>SK.draw(p,E(t,.65+i*.12,.8)));['inlet','out-a','out-b'].forEach((n,i)=>originMove(part('flow',n),{s:.8+.2*spring(t,.2+i*.65),o:E(t,.2+i*.65,.12)},400,300));qa('.label').forEach((el,i)=>SK.enter(el,t-[.4,1.3,1.7,0][i],'fade'));const pp=SK.tip(part('flow','split').querySelector('path'),E(t,1.5,1.1));traveler.setAttribute('cx',pp.x);traveler.setAttribute('cy',pp.y);traveler.style.opacity=t>=1.5&&t<3?1:0;"""
style['mg-flow']='.label{color:#f1eee5}.headline{z-index:5}.art{background:#f1eee5;border-radius:32px;padding:16px}.node-b,.node-c{color:#171918}'
body['wb-flow']=title(['THINK IT THROUGH.'],size=126,y=173,width=1690)+art('sketch','wb','logic-flow',80,0,1660)+label('idea',242,550,260,'sk-hand',96)+label('make',1090,550,380,'sk-hand',96)+label('Draft → connect → refine',99,902,1050,size=26)+'<div class="pen" aria-hidden="true"><svg viewBox="0 0 80 160"><path d="M20 25h39v99L41 156L20 124Z" fill="#244bff" stroke="#171918" stroke-width="4"/><path d="M20 124h39L41 156Z" fill="#171918"/></svg></div>'
anim['wb-flow']="""words(t,.12,0,'rise');const tip=SK.drawSeq(t,ink,{speed:1600,boil:.7});pen(tip,80,0,1660);qa('.label.sk-hand').forEach((el,i)=>SK.write(el,E(t,.9+i*1.45,.6)));"""
style['wb-flow']='.headline{color:#171918}.pen{position:absolute;width:66px;height:132px;z-index:7;transform-origin:50% 100%}.label.sk-hand{color:#171918}'
body['wb-loop']=title(['IDEAS','CONNECT.'],size=157,y=286,width=850)+art('sketch','wb','feedback-loop',817,142,1010)+label('make',1170,354,240,'sk-hand',87)+label('learn',1190,606,270,'sk-hand',87)+label('Keep the loop alive.',98,814,850,'sk-serif',67)+'<div class="pen" aria-hidden="true"><svg viewBox="0 0 80 160"><path d="M20 25h39v99L41 156L20 124Z" fill="#fa593d" stroke="#171918" stroke-width="4"/><path d="M20 124h39L41 156Z" fill="#171918"/></svg></div>'
anim['wb-loop']="""words(t,.12,.3,'mask');const tip=SK.drawSeq(t,ink,{speed:900,boil:.65});pen(tip,817,142,1010);qa('.label.sk-hand').forEach((el,i)=>SK.write(el,E(t,.65+i*1.25,.6)));"""
style['wb-loop']=style['wb-flow']
body['stop-fan']=title(['FOLD A','POSSIBILITY.'],size=146,y=195,width=1600)+art('fan','stop','paper-fan',613,205,1250)+art('card','stop','torn-card',20,514,720)+label('fold it.<br/>feel it.',160,708,360,'sk-hand',70)+label('ON TWOS / 15 POSES PER SECOND',100,916,1150,size=24)
anim['stop-fan']="""words(t,.08,.26,'slam');parts('fan','leaf-').forEach((el,i)=>{const u=E(t,.45+i*.1,.32);originMove(el,{r:(i-4)*12*(1-u),s:.15+.85*u,o:t>=.45+i*.1?1:0},400,450);});piece(a('card'),{x:-420*(1-E(t,1.25,.35)),r:-7,o:t>=1.25?1:0},3,t);qa('.label').forEach((el,i)=>SK.write(el,E(t,1.7+i*.2,.6)));"""
style['stop-fan']='.headline{z-index:5}.label.sk-hand{z-index:5}.art[data-art=card]{height:520px!important}'
body['stop-envelope']=title(['SEND','THE IDEA.'],size=166,y=291,width=880)+art('envelope','stop','open-envelope',860,208,930)+art('plane','stop','folded-plane',1205,100,340)+label('A small gesture. A new direction.',98,842,1330,'sk-hand',65)
anim['stop-envelope']="""words(t,.08,.3,'drop');piece(a('envelope'),{y:260*(1-E(t,.2,.4)),r:-4,o:t>=.2?1:0},5,t);const flap=part('envelope','flap');flap.style.transformOrigin='400px 213px';flap.style.transform='scaleY('+(-1+2*E(t,.5,.35))+')';originMove(part('envelope','card'),{y:180*(1-E(t,.85,.6)),o:1},400,300);piece(a('plane'),{x:700*(1-E(t,1.8,.5))-150*E(t,2.9,.5),y:50*E(t,2.9,.5),r:-12,o:t>=1.8?1:0},9,t);"""
body['vox-detail']=art('document','vox','note-page',130,69,1050)+f'<div class="doc-copy sk-serif"><span class="doc-kicker sk-mono">DESIGN NOTES</span><div>Motion carries<br/><span class="highlight-wrap"><i class="hl"></i>meaning.</span></div></div>'+title(['FOLLOW','THE DETAIL.'],x=1110,y=288,size=117,width=750)+label('ILUSTRASI / ORIGINAL DESIGN STUDY',98,913,1200,size=25)+art('callout','vox','data-bracket',1051,461,700)
anim['vox-detail']="""words(t,.1,.3,'rise');const u=E(t,.1,.65);piece(a('document'),{y:70*(1-u),r:-2,o:1},2,t);move(q('.doc-copy'),{y:70*(1-u),r:-2});q('.hl').style.transform='scaleX('+E(t,1.45,.6)+')';move(a('callout'),{s:.8+.2*E(t,2.15,.3),o:t>=2.15?1:0});"""
style['vox-detail']='.doc-copy{position:absolute;left:423px;top:307px;width:550px;font-size:84px;line-height:1.04;color:#171918;z-index:4;transform-origin:0 0}.doc-kicker{display:block;font-size:24px;margin-bottom:44px;letter-spacing:3px}.highlight-wrap{position:relative}.hl{position:absolute;left:-10px;right:-8px;top:16px;bottom:0;background:#ffe14d;transform-origin:left;z-index:-1}.art[data-art=document] [data-part=notes]{opacity:0}.art[data-art=callout] [data-part=center]{opacity:0}'
body['vox-timeline']=title(['SEE THE CONNECTION.'],size=122,y=178,width=1730)+art('timeline','vox','editorial-timeline',55,100,1780)+label('Form',282,533,210,'sk-serif',53)+label('Rhythm',660,735,210,'sk-serif',53)+label('Material',1038,533,210,'sk-serif',53)+label('Story',1417,735,210,'sk-serif',53)+label('ILUSTRASI / EDITORIAL MOTION STUDY',99,930,1100,size=25)
anim['vox-timeline']="""words(t,.08,.3,'mask');SK.draw(part('timeline','axis').querySelector('path'),E(t,.65,.65));parts('timeline','event-').forEach((el,i)=>originMove(el,{y:-100*(1-E(t,1+i*.35,.25)),o:t>=1+i*.35?1:0},400,300));qa('.label.sk-serif').forEach((el,i)=>SK.enter(el,t-(1.2+i*.35),'rise'));"""
style['vox-timeline']='.art[data-art=timeline] [data-part=axis] path{stroke:#fa593d}.label.sk-serif{color:#171918}.headline{z-index:4}'
body['mm-story']=art('rip','mm','ripped-stack',-190,157,980)+art('film','mm','film-perforations',1145,67,980)+art('frame','mm','taped-frame',1200,475,730)+placeholder(850,244)+title(['MAKE SPACE','FOR STORY.'],x=87,y=224,size=110,width=1000)+label('TEMPLATE / REAL MATTE IN PRODUCTION',83,934,850,size=23)+art('sticker','mm','zigzag-sticker',265,614,335)
anim['mm-story']="""words(t,.1,.3,'slam');['rip','film','frame','sticker'].forEach((n,i)=>piece(a(n),{x:(i%2?600:-500)*(1-E(t,.15+i*.3,.35)),y:70*(1-E(t,.15+i*.3,.35)),r:[-8,9,-7,12][i],o:t>=.15+i*.3?1:0},i+1,t));"""
style['mm-story']='.headline{z-index:5;top:175px!important}.speaker{position:absolute;z-index:4}.speaker-note{position:absolute;left:45px;top:469px;width:330px;text-align:center;font-size:24px;color:#f1eee5}.label{z-index:5}.art[data-art=frame]{z-index:3}.art[data-art=rip]{z-index:1}'
body['mm-play']=art('mesh','mm','mesh-circle',1170,73,640)+art('poster','mm','poster-fold',1035,359,850)+art('ink','mm','halftone-shadow',105,247,940)+f'<div class="pastewords" data-layout-allow-overlap>'+''.join(f'<div class="pasteword pw{i} sk-display">{s}</div>' for i,s in enumerate(['CUT.','PASTE.','PLAY.']))+'</div>'+art('tag','mm','tag-string',-23,633,350)+label('LIVE TYPE / PAPER / XEROX / LAYERS',96,935,1450,size=25)
anim['mm-play']="""qa('.pasteword').forEach((el,i)=>piece(el,{y:-600*(1-E(t,.1+i*.45,.2)),r:[-4,3,-2][i],o:t>=.1+i*.45?1:0},i+11,t));piece(a('mesh'),{r:12,o:t>=.2?1:0},4,t);piece(a('poster'),{x:700*(1-E(t,1.65,.35)),r:8,o:t>=1.65?1:0},5,t);piece(a('tag'),{r:-12,o:t>=2.2?1:0},6,t);"""
style['mm-play']='.pastewords{position:absolute;left:98px;top:210px;z-index:5}.pasteword{font-size:174px;line-height:.92;letter-spacing:-9px;display:table;padding:10px 20px;background:#f1eee5;color:#171918}.pw1{background:#244bff;color:#f1eee5;margin-left:73px}.pw2{background:#fa593d;margin-left:28px}.art[data-art=ink]{opacity:.28}'
def plane(name,family,asset,z,blur=0):
    return f'<div class="plane" data-z="{z}" data-blur="{blur}">'+art(name,family,asset,-180,-195,2280,1710)+'</div>'
body['px-mountains']='<div class="view"><div class="world"><div class="plane sky" data-z="-1800" data-blur="0"></div>'+plane('mountain','px','mountain-back',-1400,3)+plane('ridge','px','ridge-mid',-600,1)+plane('trees','px','pine-foreground',-70,0)+'</div></div>'+title(['ROOM TO','IMAGINE.'],size=153,y=285,width=1250)+label('ORIGINAL VECTOR WORLD / THREE DEPTH PLANES',96,907,1300,size=24)
anim['px-mountains']="""words(t,.1,.4,'rise');const u=E(t,.15,2.8);SK.camera(q('.world'),{z:130*u,ry:-1.5+3*u},{ox:960,oy:540});"""
style['px-mountains']='.sky{background:linear-gradient(#1e253f 5%,#876480 63%,#edbb9f)}.headline{z-index:5;text-shadow:0 2px 18px rgba(23,25,24,.16)}.label{z-index:6}.plane[data-z="-1400"] .art{top:-100px!important}.plane[data-z="-600"] .art{top:-440px!important}.plane[data-z="-70"] .art{top:-430px!important;left:-90px!important;width:2100px!important;height:1575px!important}'
body['px-city']='<div class="view"><div class="world"><div class="plane sky" data-z="-1800" data-blur="0"></div>'+plane('sun','px','sun-haze',-1600,0)+plane('city','px','city-back',-1200,3)+plane('tower','px','tower-mid',-500,0)+plane('rail','px','railing-front',-60,0)+'</div></div>'+title(['A DIFFERENT','POINT OF VIEW.'],size=138,y=282,width=1670)+label('ORIGINAL ILLUSTRATION / RESTRAINED CAMERA TRAVEL',96,907,1500,size=24)
anim['px-city']="""words(t,.08,.4,'mask');SK.camera(q('.world'),{x:-35+70*E(t,.15,3),z:50},{ox:960,oy:540});"""
style['px-city']='.sky{background:linear-gradient(#232941 0%,#9a738f 56%,#e7b699)}.plane[data-z="-1200"] .art{top:-70px!important;left:0!important;width:1920px!important;height:1440px!important}.plane[data-z="-500"] .art{top:80px!important;left:180px!important;width:1600px!important;height:1200px!important}.plane[data-z="-1600"] .art{left:280px!important;top:-100px!important;width:1580px!important;height:1185px!important}.plane[data-z="-60"] .art{top:-320px!important;left:-90px!important;width:2100px!important;height:1575px!important}.headline{z-index:5;text-shadow:0 4px 25px #171918}.label{z-index:5}'
body['material']=title(['MATTER','IN MOTION.'],size=169,y=275,width=1240)+art('ribbon','showreel','chrome-ribbon',890,45,1070)+art('prism','showreel','prism-facet',1230,601,425)+art('star','showreel','extruded-star',107,657,240)+label('SCULPTURAL SURFACES / ORIGINAL VECTOR MATERIALS',99,929,1540,size=24)+label('form, light, feeling.',97,764,900,'sk-serif',74)
anim['material']="""words(t,.1,.35,'mask');const light=E(t,.6,2.8);move(a('ribbon'),{r:-18+28*E(t,.2,3),s:.65+.35*E(t,.2,1.1),o:E(t,.2,.1)});move(part('ribbon','highlight'),{x:-26+52*light,y:10-20*light,o:.3+.6*Math.sin(Math.PI*light)});move(a('prism'),{y:280*(1-E(t,1.6,.7)),r:12*E(t,1.6,.7),o:E(t,1.6,.1)});part('prism','left').style.filter='brightness('+(1.15-.3*light)+')';part('prism','right').style.filter='brightness('+(.8+.4*light)+')';part('prism','edge').style.opacity=.4+.5*light;move(a('star'),{r:120*E(t,.8,2.7),s:.1+.9*spring(t,.8),o:E(t,.8,.1)});move(part('star','extrusion'),{x:-5+10*light,y:4-8*light});part('star','bevel').style.opacity=.35+.6*light;"""
style['material']='.headline{z-index:5}.label.sk-serif{left:360px!important;top:803px!important;font-size:60px!important;width:790px!important}.art[data-art=ribbon]{z-index:2}'
body['finale']=title(['RICHER','BY DESIGN.'],size=172,y=211,width=1350)+art('petal','showreel','sculpted-petal',1055,104,810)+art('orbits','showreel','orbital-trail',1040,103,850)+label('ATELIER / 112 ORIGINAL LAYERED ASSETS',98,716,1330,size=29)+label('Ideas that refuse to sit still.',98,811,1540,'sk-serif',81)
anim['finale']="""words(t,.08,.4,'slam');move(a('petal'),{r:-40+60*E(t,.15,3.4),s:.25+.75*E(t,.15,.8),o:E(t,.15,.1)});parts('petal','petal-').forEach((el,i)=>{const u=E(t,.3+i*.09,2.9-i*.09);originMove(el,{r:(i-2.5)*6*(1-u),s:.84+.16*u,o:.55+.45*u},400,300);});move(a('orbits'),{r:-30*E(t,.15,3.4),o:.45*E(t,.6,.6)});parts('orbits','orbit-').forEach((el,i)=>{const u=E(t,.6+i*.035,2.4);originMove(el,{r:(i%2?1:-1)*18*(1-u),o:.25+.65*u},400,300);});qa('.label').forEach((el,i)=>SK.enter(el,t-(1.25+i*.35),'rise'));"""
style['finale']='.headline{z-index:5}.art[data-art=orbits]{z-index:1}.art[data-art=petal]{z-index:2}.headline .mask:first-child{color:#d9fc59}.label{z-index:5}'

base='''#root{position:absolute;inset:0;width:1920px;height:1080px}.fill{position:absolute;inset:0}.grid{position:absolute;inset:75px;background-image:linear-gradient(currentColor 1px,transparent 1px),linear-gradient(90deg,currentColor 1px,transparent 1px);background-size:160px 160px;opacity:.055}.art{position:absolute;transform-origin:50% 50%}.art svg{display:block;width:100%;height:100%;overflow:visible}.headline{position:absolute;line-height:.98;letter-spacing:-.055em;z-index:3}.mask{overflow:hidden;padding:.12em .04em .15em .01em;margin:-.08em -.04em -.11em -.01em}.word{display:block;transform-origin:left center;white-space:nowrap}.label{position:absolute;line-height:1.2;z-index:3}.label.sk-hand{line-height:1}.topbar,.bottom{position:absolute;left:82px;right:82px;display:flex;justify-content:space-between;align-items:center;font-size:23px;z-index:10}.topbar{top:64px}.bottom{bottom:55px;font-size:21px}.topbar .pill{border:1px solid currentColor;padding:8px 14px;border-radius:28px;font-size:20px}.meter{display:flex;gap:8px}.meter i{width:34px;height:5px;background:currentColor;opacity:.2}.rule{position:absolute;left:82px;right:82px;bottom:100px;height:2px;background:currentColor;transform-origin:left}.cross{position:absolute;width:24px;height:24px;z-index:10}.cross:before,.cross:after{content:'';position:absolute;background:currentColor}.cross:before{left:0;top:11px;width:24px;height:2px}.cross:after{left:11px;top:0;width:2px;height:24px}.view{position:absolute;inset:0;perspective:1200px;perspective-origin:960px 540px}.world{position:absolute;inset:0;transform-style:preserve-3d}.plane{position:absolute;inset:0;width:1920px;height:1080px;backface-visibility:hidden;transform-style:preserve-3d}.speaker{position:absolute;z-index:4}.speaker-note{position:absolute;left:45px;top:469px;width:330px;text-align:center;font-size:24px;color:#f1eee5}
'''
helpers='''const q=s=>root.querySelector(s),qa=s=>Array.from(root.querySelectorAll(s));const a=n=>q('[data-art="'+n+'"]');const part=(n,p)=>a(n).querySelector('[data-part="'+p+'"]');const parts=(n,p)=>p.includes(' ')?Array.from(a(n).querySelectorAll('[data-part="'+p.split(' ')[0]+'"] '+p.split(' ')[1])):Array.from(a(n).querySelectorAll('[data-part^="'+p+'"]'));const E=(t,at,d)=>M.eo(M.clamp((t-at)/d));const spring=(t,at)=>t<at?0:M.S(t-at,18,.72);
function move(el,p){el.style.transform='translate('+(p.x||0)+'px,'+(p.y||0)+'px) rotate('+(p.r||0)+'deg) scale('+(p.s??1)+')';if(p.o!=null)el.style.opacity=p.o;}
function originMove(el,p,x,y){el.style.transformOrigin=x+'px '+y+'px';move(el,p);}
function piece(el,p,seed,t){SK.piece(el,p,seed,t,{amp:1.1});}
function words(t,at,stagger,kind){qa('.word').forEach((el,i)=>SK.enter(el,t-(at+i*stagger),kind));}
function pen(tip,x,y,w){const el=q('.pen');if(!el)return;el.style.opacity=tip?1:0;if(tip)move(el,{x:x+tip.x*w/800-33,y:y+tip.y*w/800-128,r:tip.angle-70});}
'''
pal={'ink':('#171918','#f1eee5'),'paper':('#f1eee5','#171918'),'blue':('#244bff','#f1eee5'),'pink':('#b6a3ef','#171918'),'acid':('#d9fc59','#171918')}
for i,r in enumerate(rows):
    key=r['key'];cid=r['id'];bg,fg=pal[r['theme']]
    furniture=f'<div class="grid" aria-hidden="true"></div><div class="topbar sk-mono"><span>ATELIER / RICHER BY DESIGN</span><span class="pill">{r["style"].upper()}</span></div><div class="bottom sk-mono"><span>{i+1:02} / 16 — MOTION STUDY</span><div class="meter">'+''.join('<i></i>' for _ in range(8))+'</div><span>ORIGINAL / 2026</span></div><div class="rule"></div>'+''.join(f'<div class="cross" style="{pos}" aria-hidden="true"></div>' for pos in ['left:42px;top:39px','right:42px;top:39px','left:42px;bottom:32px','right:42px;bottom:32px'])
    setup=''
    if key=='mg-flow':
        setup="const traveler=document.createElementNS('http://www.w3.org/2000/svg','circle');traveler.setAttribute('r','11');traveler.setAttribute('fill','#fa593d');a('flow').querySelector('svg').appendChild(traveler);"
    if key.startswith('wb-'):
        setup="const ink=[];let at=.4;parts('sketch','stroke-').forEach(group=>group.querySelectorAll('path').forEach(el=>{const dur=SK.len(el)/"+('1600' if key=='wb-flow' else '900')+";ink.push({el,at,dur});at+=dur+.065;}));"
    if key.startswith('px-'):
        setup="qa('.plane').forEach(el=>{const z=Number(el.dataset.z);SK.layer(el,z,{fill:z>-100?1.02:1.08,ox:960,oy:540});el.style.filter='blur('+el.dataset.blur+'px)';});"
    stepped=r['style'] in ['stop-motion','vox','mix-media']
    js=f'''(()=>{{const root=document.querySelector('[data-composition-id="{cid}"]');{helpers}{setup}SK.clip('{cid}',{{T:4,W:1920,H:1080,bg:'{bg}',update:raw=>{{const t={"SK.stepTime(raw,15)" if stepped else "raw"};{anim[key]}q('.rule').style.transform='scaleX('+E(t,0,.7)+')';qa('.meter i').forEach((el,j)=>el.style.opacity=t>=j*.5?1:.2);}}}});}})();'''
    markup=f'<div id="root" data-composition-id="{cid}" data-start="0" data-duration="4" data-width="1920" data-height="1080"><div class="sk-stage" style="background:{bg};color:{fg}"><div class="fill" style="background:{bg}"></div>{body[key]}{furniture}</div></div>'
    (P/r['source']).write_text(f'<!doctype html><html lang="en"><head><meta charset="UTF-8"/><title>{r["title"]}</title></head><body><template><style>{base}{style.get(key,"")}</style>{markup}<script>{js}</script></template></body></html>')
# HyperFrames 0.7.24 includes both ends of a mount interval. Exclude the
# outgoing cut instant without removing any 30/120 fps sample, and isolate
# descendant z-index values so they cannot paint into neighboring scenes.
mounts=''.join(f'<div id="mount-{i+1:02}" class="mount" style="z-index:{i}" data-layout-allow-overlap data-layout-allow-occlusion data-composition-id="{r["id"]}" data-composition-src="{r["source"]}" data-start="{i*4}" data-duration="{4 if i==len(rows)-1 else 3.999999}" data-track-index="1" data-width="1920" data-height="1080"></div>' for i,r in enumerate(rows))
host=f'''<!doctype html><html lang="en"><head><meta charset="UTF-8"/><title>ATELIER / Richer by Design</title><script src="vendor/gsap.min.js"></script><script src="vendor/motion-kit.js"></script><script src="vendor/style-kit.js"></script><link rel="stylesheet" href="assets/design.css"/><style>html,body{{margin:0;width:1920px;height:1080px;overflow:hidden;background:#171918}}#stage{{position:relative;width:1920px;height:1080px;overflow:hidden}}.mount{{position:absolute;inset:0;width:1920px;height:1080px;isolation:isolate}}audio.clip{{position:absolute;width:0;height:0;opacity:0}}</style></head><body><div id="stage" data-composition-id="style-atelier" data-start="0" data-duration="64" data-width="1920" data-height="1080" data-fps="30">{mounts}<audio id="master" class="clip" src="assets/audio/master.wav" data-start="0" data-duration="64" data-track-index="20" data-volume="1"></audio></div><script>window.__timelines=window.__timelines||{{}};window.__timelines['style-atelier']=gsap.timeline({{paused:true}});</script></body></html>'''
(P/'index.html').write_text(host)
print('Built sixteen editable studies and 64-second Atelier host')
